version: "3"

networks:
  corp:
    driver: bridge

services:
  todos-api:
    container_name: todos-api
    networks:
      - corp
    build: 
      context: .
      dockerfile: ./api.Dockerfile
    ports:
      - "4001:4001"
  todos-api1:
    container_name: todos-api1
    networks:
      - corp
    build: 
      context: .
      dockerfile: ./api.Dockerfile
    ports:
      - "4002:4001"
  todos:
    container_name: todos
    networks:
      - corp
    build: .
    volumes:
      - ./dist:/usr/share/nginx/html/dist
      - ./dist:/var/www/html/dist
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"